### PR TITLE
Build pgAgent extension based installer for v10 windows-x64

### PR DESCRIPTION
**Pull request by Semab-Tariq**
- Updated boost version in files_to_project_map.txt
- Updated paths inside settings.sh.in
- Updated windows-x64 script files
- Updated en.lng file to support pgAgent
- Adding support to build pgAgent on windows-x64 inside build.sh

### CODE REVIEW

**Comment by Semab-Tariq** [comment]
Hi, @muralikrishna05 can you please review this request?

**Review by muralikrishna05 — COMMENTED** [review]
@Semab-Tariq Changes looks good to me.

**Comment by Semab-Tariq** [comment]
Thank you @muralikrishna05 
@sandeep-edb can you please review/merge the branch?

**Comment by sandeep-edb** [comment]
I observed some changes from Visual Studio 12.0 to 14.0. Why is that done? Please remember the server and other components on v10 branch uses Visual Studio 12.0 (VC++ 2013) to build. From v11 onwards we moved to VC++ 2017

**Comment by Semab-Tariq** [comment]
@sandeep-edb I am getting this error if I try to build pgAgent with Visual Studio 12.0
```
+ ssh buildfarm@bf10-windows-x64.ox.uk.enterprisedb.com 'cd D:\\pginstaller.pune/pgAgent.windows-x64; export PGDIR=D:\\pginstaller.pune/output ; cmd /c D:\\pginstaller.pune\\vc-build-x64.bat pgagent.vcxproj RELEASE'
^M
D:\pginstaller.pune\pgAgent.windows-x64>REM Setting Visual Studio Environment ^M
^M
D:\pginstaller.pune\pgAgent.windows-x64>CALL "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\vcvarsall.bat" amd64 ^M
Microsoft (R) Build Engine version 12.0.40629.0^M
[Microsoft .NET Framework, version 4.0.30319.42000]^M
Copyright (C) Microsoft Corporation. All rights reserved.^M
^M
Build started 5/31/2021 6:00:19 AM.^M
Project "D:\pginstaller.pune\pgAgent.windows-x64\pgagent.vcxproj" on node 1 (default targets).^M
Project "D:\pginstaller.pune\pgAgent.windows-x64\pgagent.vcxproj" (1) is building "D:\pginstaller.pune\pgAgent.windows-x64\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).^M
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [D:\pginstaller.pune\pgAgent.windows-x64\ZERO_CHECK.vcxproj]^M
Done Building Project "D:\pginstaller.pune\pgAgent.windows-x64\ZERO_CHECK.vcxproj" (default targets) -- FAILED.^M
Done Building Project "D:\pginstaller.pune\pgAgent.windows-x64\pgagent.vcxproj" (default targets) -- FAILED.^M
^M
Build FAILED.^M
```

**Comment by Semab-Tariq** [comment]
@sandeep-edb Thank you for pointing this out I have reverted the changes related from VS 2014 to VS 2012 and generated the pgAgent installer
I will update here once I am finished with testing

**Comment by Semab-Tariq** [comment]
Hi @sandeep-edb 
I just push a commit to use Visual Studio 2012 for v10 can you please review it?

**Review by sandeep-edb — COMMENTED** [review]
looks good except the PG_VSINSTALLDIR_WINDOWS_X64 value in settings.sh. Changing it's value (by appending \VC) may break the server build. Can you please check?

**Comment by Semab-Tariq** [comment]
Thanks, @sandeep-edb Yes it will break server build

I removed `VC` from `PG_VSINSTALLDIR_WINDOWS_X64` and hardcode it inside` pgAgent/build-windows-x64.sh `

Please review

**Review by sandeep-edb — APPROVED** [review]

**Pull request merged**
