### PR TITLE
[PPS-94]: Adding support to build pgAgent extension based installer for v10 on macOS

### PR DESCRIPTION
**Pull request by Semab-Tariq**
I have copied pgAgent/installer.xml.in file from REL-11 branch to REL-10 branch 
All the other changes I have done manually

### CODE REVIEW

**Review by muralikrishna05 — COMMENTED** [review]
Changes are looks good to me. Please build the installer withe these changes and test it once.

**Comment by Semab-Tariq** [comment]
@muralikrishna05 I have generated the installer and done some sanity testing everything working fine

**Comment by muralikrishna05** [comment]
> @muralikrishna05 I have generated the installer and done some sanity testing everything working fine

@Semab-Tariq - Then it's fine.

**Comment by Semab-Tariq** [comment]
Thanks, @muralikrishna05 
@sandeep-edb can you please have a look and merge the changes?

**Pull request merged**
