### PR TITLE
[DB-1331] Adding support to build server with LZ4 support

### PR DESCRIPTION
**Pull request by Semab-Tariq**

### CODE REVIEW

**Comment by Semab-Tariq** [comment]
Hi @sandeep-edb can you please review/merge this request?

**Review by sandeep-edb — COMMENTED** [review]
Patch looks good to me overall. But, can u confirm if the changes done to files_to_project_map.txt file is only needed for Windows? Or for macOS also we need a change.
Also, on Windows you are copying the DLL. Don't we need the corresponding .lib to be bundled as well?

**Comment by Semab-Tariq** [comment]
Hi @sandeep-edb 

1) 
When I saw this `files_to_project_map.txt` file I only found `.dll` and `.exe` files I don't see any `.so` or `.dylib` file so I thought it is only for Windows.

I spoke with Basha about adding macOS libraries names inside `files_to_project_map.txt` he says 

> i think there is no separate file for mac so try to add there for mac and build and check with Sandeep after that.

So I added macOS libraries names there and then generated both macOS and Windows64 installers against and checked License files and `LZ4` support everything is working as expected.

2) 
I guess `LZ4` support is working fine by only copying `liblz4.dll` inside `bin` so I didn't think of copying `liblz4.lib` in `lib` 
But if you still think we should add `.lib` as well I can do that.

**Review by sandeep-edb — COMMENTED** [review]
Also, I think we must use the contents of https://github.com/lz4/lz4/blob/dev/lib/LICENSE in liblz4_license.txt

**Comment by Semab-Tariq** [comment]
Hi @sandeep-edb please review the latest commit

**Pull request merged**
